# yaml-language-server: $schema=../schema.json
chainId: 1003202503
displayName: Affogato Venti
domainId: 1003202503
index:
  from: 10
isTestnet: true
name: venti
nativeToken:
  decimals: 18
  name: Ether
  symbol: ETH
protocol: ethereum
rpcUrls:
  - http: http://localhost:9550
technicalStack: arbitrumnitro
